on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ staging ]

jobs:
  rubocop:
    name: Run rubocop autofix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Team App)
        uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1.101.0
        with:
          ruby-version: 2.6.5
      - name: Run rubocop
        uses: Vinccool96/rubocop-linter@v1.0.1
        with:
          rubocop_extensions: ''
      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          message: 'Rubocop commit'
